package com.dokstudio.obs
import android.app.Activity;import android.content.Intent;import android.os.Bundle;import android.media.projection.MediaProjectionManager
import androidx.activity.ComponentActivity;import androidx.activity.compose.setContent;import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background;import androidx.compose.foundation.layout.*;import androidx.compose.foundation.lazy.LazyColumn;import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*;import androidx.compose.runtime.*;import androidx.compose.ui.Alignment;import androidx.compose.ui.Modifier;import androidx.compose.ui.graphics.Color;import androidx.compose.ui.unit.dp;import androidx.lifecycle.viewmodel.compose.viewModel
import com.dokstudio.obs.engine.StudioState;import com.dokstudio.obs.permissions.PermissionCoordinator;import com.dokstudio.obs.recording.*
class MainActivity:ComponentActivity(){private lateinit var recording:RecordingController;private var projectionResult:Int?=null;private var projectionData:Intent?=null
 private val launcher=registerForActivityResult(ActivityResultContracts.StartActivityForResult()){r->if(r.resultCode==Activity.RESULT_OK&&r.data!=null){projectionResult=r.resultCode;projectionData=r.data}}
 override fun onCreate(b:Bundle?){super.onCreate(b);recording=RecordingController(this);PermissionCoordinator(this).request();setContent{MaterialTheme{StudioScreen(this,launcher)}}}
 fun startRecording(vm:com.dokstudio.obs.ui.StudioViewModel,onError:(String)->Unit){val code=projectionResult;val data=projectionData;if(code==null||data==null){onError("Grant Screen Capture consent first.");return};startService(Intent(this,service.StudioForegroundService::class.java));recording.start(code,data,1280,720,30,6000000,{vm.engine.markRecording()},{t->vm.engine.idle();onError(t.message?:"Recording failed")})}
 fun stopRecording(vm:com.dokstudio.obs.ui.StudioViewModel){recording.stop();vm.engine.idle()}}
@Composable private fun StudioScreen(a:MainActivity,launcher:androidx.activity.result.ActivityResultLauncher<Intent>,vm:com.dokstudio.obs.ui.StudioViewModel=viewModel()){val scenes by vm.scenes.collectAsState();val studio by vm.engine.studio.collectAsState();var error by remember{mutableStateOf<String?>(null)};Column(Modifier.fillMaxSize().background(Color(0xFF101114)).padding(16.dp)){Text("OBS Dok Studio",color=Color.White,style=MaterialTheme.typography.headlineSmall);Spacer(Modifier.height(12.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(enabled=studio==StudioState.IDLE,onClick={vm.engine.prepare();vm.engine.ready()}){Text("Prepare")};Button(enabled=studio==StudioState.READY,onClick={launcher.launch(a.getSystemService(MediaProjectionManager::class.java).createScreenCaptureIntent())}){Text("Screen Consent")};Button(enabled=studio==StudioState.READY,onClick={a.startRecording(vm){error=it}}){Text("Record")};Button(enabled=studio==StudioState.RECORDING,onClick={a.stopRecording(vm)}){Text("Stop")}};Text("State: "+studio,color=Color.White);error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Spacer(Modifier.height(12.dp));Text("Encoder profiles",color=Color.White);EncoderCapabilities.profiles().forEach{(p,ok)->Text(p.name+" — "+p.width+"x"+p.height+" @ "+p.fps+" : "+if(ok)"supported" else "unsupported",color=Color.LightGray)};Spacer(Modifier.height(12.dp));Box(Modifier.fillMaxWidth().height(220.dp).background(Color(0xFF202226)),contentAlignment=Alignment.Center){Text("Native preview surface is attached by the compositor when a source is bound.",color=Color.Gray)};scenes.firstOrNull()?.let{s->Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick={vm.addSource(s.id,"SCREEN")}){Text("Screen Source")};Button(onClick={vm.addSource(s.id,"CAMERA")}){Text("Camera Source")};Button(onClick={vm.addSource(s.id,"MICROPHONE")}){Text("Mic Source")}}};LazyColumn{items(scenes){Text(it.name,color=Color.White,modifier=Modifier.padding(8.dp))}}}}
